apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Dminus251/practice-gitOps #git repo 주소
    targetRevision: main 
    path: argo-cd/ # Helm 차트가 위치한 경로
    helm:
      valueFiles:
        - values.yaml
