apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Dminus251/practice-gitOps
    targetRevision: HEAD
    path: argo-rollouts/

  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
